"""init

Revision ID: 1eaaea1e056f
Revises:
Create Date: 2026-08-08 21:53:32.753031

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "1eaaea1e056f"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
